// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/tempconv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Temperature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	mi := &file_proto_tempconv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tempconv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_proto_tempconv_proto_rawDescGZIP(), []int{0}
}

func (x *Temperature) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_proto_tempconv_proto protoreflect.FileDescriptor

const file_proto_tempconv_proto_rawDesc = "" +
	"\n" +
	"\x14proto/tempconv.proto\x12\btempconv\"#\n" +
	"\vTemperature\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value2\x9b\x01\n" +
	"\x0fTempConvService\x12C\n" +
	"\x13CelsiusToFahrenheit\x12\x15.tempconv.Temperature\x1a\x15.tempconv.Temperature\x12C\n" +
	"\x13FahrenheitToCelsius\x12\x15.tempconv.Temperature\x1a\x15.tempconv.TemperatureB/Z-github.com/MMohammadinia/tempconv/proto;protob\x06proto3"

var (
	file_proto_tempconv_proto_rawDescOnce sync.Once
	file_proto_tempconv_proto_rawDescData []byte
)

func file_proto_tempconv_proto_rawDescGZIP() []byte {
	file_proto_tempconv_proto_rawDescOnce.Do(func() {
		file_proto_tempconv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tempconv_proto_rawDesc), len(file_proto_tempconv_proto_rawDesc)))
	})
	return file_proto_tempconv_proto_rawDescData
}

var file_proto_tempconv_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_tempconv_proto_goTypes = []any{
	(*Temperature)(nil), // 0: tempconv.Temperature
}
var file_proto_tempconv_proto_depIdxs = []int32{
	0, // 0: tempconv.TempConvService.CelsiusToFahrenheit:input_type -> tempconv.Temperature
	0, // 1: tempconv.TempConvService.FahrenheitToCelsius:input_type -> tempconv.Temperature
	0, // 2: tempconv.TempConvService.CelsiusToFahrenheit:output_type -> tempconv.Temperature
	0, // 3: tempconv.TempConvService.FahrenheitToCelsius:output_type -> tempconv.Temperature
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tempconv_proto_init() }
func file_proto_tempconv_proto_init() {
	if File_proto_tempconv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tempconv_proto_rawDesc), len(file_proto_tempconv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tempconv_proto_goTypes,
		DependencyIndexes: file_proto_tempconv_proto_depIdxs,
		MessageInfos:      file_proto_tempconv_proto_msgTypes,
	}.Build()
	File_proto_tempconv_proto = out.File
	file_proto_tempconv_proto_goTypes = nil
	file_proto_tempconv_proto_depIdxs = nil
}
